server:
  port: 7900

spring:
  application:
    name: sso-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.134:3306/test1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: chen521...
  redis:
    database: 0
    host: 192.168.137.134
    port: 6379
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.dragon.pojo
  mapperLocations: classpath:mybatis/mappers/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  eureka:
    enable: true

logging:
  level:
    com.dragon.mapper: debug